William
tachorzy/COSC4353-Project-Group39 pull request #31
Opened 2023-04-06 21:31 UTC by Druasoul

Ok, just resending another pull request. It has the register which now work, it also set the ProfileSet to false so that the first time someone login. They would be send to the ProfileForm. Just need to update the Profile form I already send an issue about it.

2023-04-06 22:39 UTC, tachorzy requested changes
I said the same to Tina: Avoid using inline CSS styling like on lines 101-108 in `ProfileForm.jsx`. We chose to use TailwindCSS and you can use inline for example like className={bg-black absolute} or you can write that TailwindCSS in one of the files in the styles folder (you'll want to use the one that's imported in this file and if there isn't one already you can go ahead and create it).

2023-04-07 00:17 UTC, Druasoul commented
I did not work on the ProfileForm I kinda forgot to talk about that in my uptade. I did .gitignore but ig it still went through. I am not working on that, if you can just merge the rest and ignore the profile form would be awesome!

2023-04-08 01:20 UTC, tachorzy approved these changes

2023-04-08 01:24 UTC, tachorzy approved these changes

2023-04-08 01:25 UTC, merged